home/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', home_index, name = 'home_index'),
    path('telegram', home_telegram, name = 'home_telegram'),
    path('contact', home_contact, name = 'home_contact')
]

regulus_django4/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('authentication.urls')),
    path('locations/', include('locations.urls')),
    path('books/', include('books.urls')),
    path('machines/', include('machines.urls')),
    path('unclassified-items/', include('unclassified_items.urls')),
    path('logbook/', include('logbook.urls')),
]

home/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.db.models.signals import pre_save, post_save
from django.dispatch import receiver
from autoslug import AutoSlugField
from users.models import User
from locations.models import Location
from utils import utils

# Create your models here.

class StockValidationMixin:
    def clean_stock(self):
        if self.stock < 0:
            raise ValidationError("El stock debe ser igual o mayor a cero.")


class Item(models.Model, StockValidationMixin):
    location = models.ForeignKey(Location, on_delete = models.SET_NULL,
        null = True, verbose_name = "Localización")
    code = models.CharField(max_length = 36, unique = True, 
        verbose_name = "Código")
    name = utils.name_field
    slug = utils.autoslug_field
    stock = models.PositiveSmallIntegerField(default = 0, 
                                verbose_name = "Stock")
    description = utils.optional_description_field
    
    class Meta:
        abstract = True


class ContactPerson(models.Model):

    ROLES = (
        ("trabajador", "Trabajador"),
        ("encargado", "Encargado(a)"),
        ("administrador", "Administrador"),
        ("programador", "Programador")
    )

    name = utils.name_field
    role = models.CharField(max_length = 32, choices = ROLES,
    verbose_name = "Rol")
    email = models.EmailField(verbose_name = "Email")
    phone_number = utils.phone_number_field
    phone_available = models.BooleanField(default = False,
                    verbose_name = "Puede recibir llamadas")
    whatsapp_available = models.BooleanField(default = False, 
                    verbose_name = "Tiene WhatsApp")
    telegram_available = models.BooleanField(default = False,
                    verbose_name = "Tiene Telegram")

    
    def __str__(self):
        return self.name


    class Meta:
        verbose_name = "Persona de contacto"
        verbose_name_plural = "Personas de contacto"
        db_table = "contact_person"
        ordering = ("role", )
    

home/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import MinLengthValidator
from utils import utils
from .models import *


def validate_stock(value):
	if value < 0:
		raise ValidationError('El stock no debe tener un valor negativo.')


text_field_widget = forms.TextInput(attrs = {'class': 'form-control'})

text_area_widget = forms.Textarea(attrs = 
	{'class': 'form-control', 'rows': 4}
	)

custom_name_field = forms.CharField(
	max_length = 128, 
	widget = text_field_widget,
	validators = [utils.name_validator],
	label = "Nombre")

code_field = forms.CharField(
	max_length = 30,
	widget = text_field_widget,
	validators = [MinLengthValidator(4)],
	label = "Código"
	)

stock_field = forms.IntegerField(
	validators = [validate_stock],
	widget = forms.NumberInput(
		attrs = {"class": "form-control"}),
	label = "Stock"
	)

optional_description_field = forms.CharField(required= False,
		widget= text_area_widget, label= 'Descripción')

location_field = forms.ModelChoiceField(
		queryset = Location.objects.all(),
		widget = forms.Select(
			attrs = {'class': 'form-select'}),
		label = "Localización"
		)

home/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, Http404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.conf import settings
from .models import *
from books.models import *
from machines.models import *
from unclassified_items.models import *
from .forms import *


### Vista raíz del inventario

def home_index(request):

    literature_items_count = (Book.objects.all().count() + 
        BookMaterial.objects.all().count())

    machinery_items_count = (Machine.objects.all().count() +
        MachinesSupply.objects.all().count())

    unclassified_items_count = UnclassifiedItem.objects.all().count()
    
    context = {
        "title": "Inicio - Regulus Web",
        "literature_items_count": literature_items_count,
        "machinery_items_count": machinery_items_count,
        "unclassified_items_count": unclassified_items_count,
    }

    return render(request, 'home/home_index.html',
        context)


def home_telegram(request):

    context = {
        "title": "Notificaciones por Telegram"
    }

    return render(request, 'home/home_telegram.html', context)



def home_contact(request):

    contact_persons = ContactPerson.objects.all()

    context = {
        "title": "Contacto",
        "contact_persons": contact_persons
    }

    return render(request, 'home/home_contact.html', context)

templates/home/categories_cards.html
<h2 class="text-center text-brown">Categorías</h2>
<p class="text-center">Pulse sobre el título de una categoría para acceder a su contenido. Si es un usuario autenticado, puede registrar nuevos ítems y gestionar las localizaciones.</p>

<div class="container">
    <div class="row g-3 text-center">
        <div class="col-sm-6 my-3">
            <div class="card h-100 shadow-lg border-brown">
                <a href="{% url 'books_home' %}" class="text-decoration-none"><h4 class="card-header card-title text-brown-link"><i class="fa-solid fa-book"></i> Literatura</h4></a>
                <div class="card-body">                    
                    <p class="card-text">Libros, tomos, materiales para elaboración de libros, etc.</p>
                </div>
                <div class="card-footer">
                    Items: {{literature_items_count}}
                </div>
            </div>            
        </div>        
        <div class="col-sm-6 my-3">
            <div class="card h-100 shadow-lg border-brown">
                <a href="{% url 'machines_home' %}" class="text-decoration-none"><h4 class="card-header card-title text-brown-link"><i class="fa-solid fa-print"></i> Maquinaria</h4></a>
                <div class="card-body">                    
                    <p class="card-text">Impresoras, computadores, suministros, etc.</p>
                </div>
                <div class="card-footer">
                    Items: {{machinery_items_count}}
                </div>
            </div>
        </div>
        <div class="col-sm-6 my-3">
            <div class="card h-100 shadow-lg border-brown">
                <a href='{% url "unclassified_items_home" %}' class="text-decoration-none"><h4 class="card-header card-title text-brown-link"><i class="fa-solid fa-box"></i> Sin clasificar</h4></a>
                <div class="card-body">                    
                    <p class="card-text">Items del inventario no relacionados con las otras categorías</p>
                </div>
                <div class="card-footer">
                    Items: {{unclassified_items_count}}
                </div>
            </div>
        </div>
        <div class="col-sm-6 my-3">
            <div class="card h-100 shadow-lg border-brown">
                <a href="{% url 'locations_home' %}" class="text-decoration-none"><h4 class="card-header card-title text-purple"><i class="fa-solid fa-warehouse"></i> Localizaciones</h4></a>
                <div class="card-body">                    
                    <p class="card-text">En esta sección, puede gestionar las localizaciones o ubicaciones en el espacio físico. Se debe asignar una localización a todos los ítems registrados.</p>
                </div>
            </div>
        </div>
    </div>
</div>

templates/home/home_contact.html
{% extends 'base/base.html' %} {% load static %}

{% block title %}{{ title }}{% endblock %}

{% block body %}
<div class="container-fluid rounded px-5 py-4 bg-white">

    <h1 class="text-brown text-center">{{ title }}</h1>
    <p>
        En esta sección encontrará la información de contacto de las personas
        a cargo, ya sea para hacer consultas o solicitudes. En cada contacto, tendrá a
        su disposición la dirección de correo electrónico, el número telefónico, y los 
        medios por los cuales puede ser contactada cada persona.
    </p>
    <hr class="text-brown">
    <section class="container-fluid px-2">
        <div class="row g-3">
        {% for person in contact_persons %}
            <div class="col-md-6">
                    <h5>{{person.name}}</h5>
                    <p><span class="fw-bold">Rol: </span>{{person.get_role_display}}</p>
                    <p><span class="fw-bold">Email: </span>{{person.email}}</p>
                    <p><span class="fw-bold">Teléfono: </span>{{person.phone_number}}</p>
                <div>
                    <p class="h4">
                        {% if person.phone_available %}
                        <i class="fa-solid fa-phone"></i>
                        {% endif %}
                        {% if person.whatsapp_available %}
                        <i class="fa-brands fa-whatsapp text-success"></i>
                        {% endif %}
                        {% if person.telegram_available %}
                        <i class="fa-brands fa-telegram text-primary"></i>
                        {% endif %}
                    </p>
                </div>
                <hr>
            </div>
        {% endfor %}
        </div>
    </section>
</div>
{% endblock %}

templates/home/home_index.html
{% extends 'base/base.html' %} {% load static %}

{% block title %}{{title}}{% endblock title %}

{% block body %}

{% include 'base/base_messages.html' %}

<div class="container-fluid rounded px-5 py-4 bg-white">

    <h1 class="text-center text-green">Regulus Web - Imprenta LDO</h1>

    <hr class="text-brown">
    
    <p>
        Bienvenido(a) a Regulus Web, sistema online para gestionar el inventario de su imprenta. 
        Tendrá a su disposición distintas categorías en las cuales se clasifican los ítems guardados en este inventario.
    </p>
    
    <p>
        La sección de <b>Literatura</b> le permitirá registrar libros, tomos, materiales, accesorios, etc.
    </p>
    
    <p>
        La sección de <b>Maquinaria</b> le permitirá registrar impresoras, insumos, accesorios.
    </p>
    
    <p>
        La sección de <b>Otros ítems</b> le permitirá registrar ítems que no quepan en las secciones anteriores.
    </p>

    <p>
        La sección de <b>Localizacioes</b> muestra las localizaciones registradas en el inventario, donde se
        guardarán los ítems.
    </p>

    <p>
        La sección de <b>Bitácora</b> le permitirá crear registros personalizados.
    </p>
    
    <p>Aunque la web se adapte al tamaño de las pantallas, se recomienda que, si está accediendo desde un móvil o tablet, lo haga en modo horizontal.</p>

</div>

{% endblock body %}

templates/home/home_telegram.html
{% extends 'base/base.html' %} {% load static %}

{% block title %}{{ title }}{% endblock %}

{% block body %}

<div class="container-fluid rounded px-5 py-4 bg-white">

    <h1 class="text-telegram-blue text-center">{{ title }}</h1>
    <p><span class="text-green"><strong>Regulus Web</strong></span> envía notificaciones por Telegram por medio de un Bot configurado previamente,
        acerca de los ítems creados en en inventario, actualización de stock y creación de registros personalizados en 
        la bitácora. Esto permite que las personas involucradas estén informadas oportunamente de cada cambio realizado en el
        inventario.
    </p>

    <p>Se utiliza Telegram porque esta app es rápida, eficiente y lo suficientemente segura, 
        además de que permite utilizar su API de forma gratuita.</p>

    <p>Para aprovechar esta funcionalidad, se crea un Bot y se determina qué usuario o grupo recibirá las notificaciones.
        Una vez se tiene ambos, se debe contactar al administrador, y luego al programador (o persona capacitada) para registrar
        esos datos en las variables de entorno de <span class="text-green"><strong>Regulus Web</strong></span>.
    </p>

    <p>
        En cualquier caso, si no se configura el Bot ni el usuario/grupo de Telegram, el sistema sigue funcionando
        correctamente,solo que no se enviarán las notificaciones.
    </p>
</div>

{% endblock %}