home/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', home_index, name = 'home_index'),
    path('telegram', home_telegram, name = 'home_telegram'),
    path('contact', home_contact, name = 'home_contact')
]

logbook/urls.py
from django.urls import path
from .views import *


urlpatterns = [
	path('', logbook_home, name = "logbook_home"),
	path('new-custom-log/', logbook_new_custom_log,
		name = "logbook_new_custom_log"),
	path('custom-log-detail/<int:id>', logbook_custom_log_detail,
		name = "logbook_custom_log_detail"),
	path("switch-custom-log-archived-status/<int:id>", 
		logbook_switch_custom_log_archived_status,
		name = "logbook_switch_custom_log_archived_status"),
]

regulus_django4/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('authentication.urls')),
    path('locations/', include('locations.urls')),
    path('books/', include('books.urls')),
    path('machines/', include('machines.urls')),
    path('unclassified-items/', include('unclassified_items.urls')),
    path('logbook/', include('logbook.urls')),
]

logbook/models.py
import uuid
import random
import string
from django.db import models
from django.utils import timezone
from autoslug import AutoSlugField
from users.models import User
from books.models import Book, BookMaterial
from machines.models import Machine, MachinesSupply
from unclassified_items.models import UnclassifiedItem
from utils import utils


def generate_code():
	while True:
		code = ''.join(random.choice(string.digits) for _ in range(12))
		if not CustomLog.objects.filter(code = code).exists():
			return code


PRIORITIES = (
	("baja", "Baja"),
	("normal", "Normal"),
	("alta", "Alta"),
)

ITEM_LOG_TYPES = (
	("creacion_item", "Creación de ítem"),
	("suma", "Stock añadido"),
	("resta", "Stock restado"),
	("actualizacion_datos", "Actualización de datos"),
)

CUSTOM_LOG_TYPES = (
	("ingreso_persona", "Ingreso de persona"),
	("salida_persona", "Salida de persona"),
	("inicio_jornada", "Inicio de jornada"),
	("termino_jornada", "Término de jornada"),
	("otros", "Otros / Sin clasificar")
)


class ItemLog(models.Model):

	user = models.ForeignKey(User, on_delete = models.SET_NULL,
		null = True, verbose_name = "Usuario")
	book = models.ForeignKey(Book, on_delete = models.SET_NULL,
		null = True, verbose_name = "Libro")
	book_material = models.ForeignKey(BookMaterial, 
		on_delete = models.SET_NULL, null = True,
		verbose_name = "Material para libros")
	machine = models.ForeignKey(Machine, on_delete = models.SET_NULL,
		null = True, verbose_name = "Máquina")
	machines_supply = models.ForeignKey(MachinesSupply, 
		on_delete = models.SET_NULL, null = True,
		verbose_name = "Suministro para Maquinaria")
	unclassified_item = models.ForeignKey(UnclassifiedItem,
		on_delete = models.SET_NULL, null = True,
		verbose_name = "Ítem sin clasificar")
	log_type = models.CharField(max_length = 128, choices = ITEM_LOG_TYPES,
		verbose_name = "Tipo de registro")
	previous_stock = models.PositiveSmallIntegerField(
		default = 0, verbose_name = "Stock previo")
	updated_stock = models.PositiveSmallIntegerField(
		default = 0, verbose_name = "Stock nuevo")
	created_on = models.DateTimeField(default = timezone.now,
		verbose_name = "Creación")


	def __str__(self):
		return f"{self.created_on}"


	class Meta:
		verbose_name = "Registro de ítems"
		verbose_name_plural = "Registros de ítems"
		db_table = "item_log"


class BookLog(models.Model):

	user = models.ForeignKey(User, on_delete = models.SET_NULL,
	null = True, verbose_name = "Usuario")
	book = models.ForeignKey(Book, on_delete = models.SET_NULL,
	null = True, verbose_name = "Libro")
	log_type = models.CharField(max_length = 128, choices = ITEM_LOG_TYPES,
		verbose_name = "Tipo de registro")
	previous_stock = models.PositiveSmallIntegerField(
		default = 0, verbose_name = "Stock previo")
	updated_stock = models.PositiveSmallIntegerField(
		default = 0, verbose_name = "Stock nuevo")
	created_on = models.DateTimeField(default = timezone.now,
		verbose_name = "Creación")


	def __str__(self):
		return f"{self.created_on}"


	class Meta:
		verbose_name = "Registro de Libro"
		verbose_name_plural = "Registros de Libro"
		db_table = "book_log"


class BookMaterialLog(models.Model):

	user = models.ForeignKey(User, on_delete = models.SET_NULL,
	null = True, verbose_name = "Usuario")
	book_material = models.ForeignKey(BookMaterial, on_delete = models.SET_NULL,
	null = True, verbose_name = "Material para Libros")
	log_type = models.CharField(max_length = 128, choices = ITEM_LOG_TYPES,
		verbose_name = "Tipo de registro")
	previous_stock = models.PositiveSmallIntegerField(
		default = 0, verbose_name = "Stock previo")
	updated_stock = models.PositiveSmallIntegerField(
		default = 0, verbose_name = "Stock nuevo")
	created_on = models.DateTimeField(default = timezone.now,
		verbose_name = "Creación")


	def __str__(self):
		return f"{self.created_on}"


	class Meta:
		verbose_name = "Registro de Material para Libros"
		verbose_name_plural = "Registros de Material para Libros"
		db_table = "book_material_log"


class MachineLog(models.Model):

	user = models.ForeignKey(User, on_delete = models.SET_NULL,
	null = True, verbose_name = "Usuario")
	machine = models.ForeignKey(Machine, on_delete = models.SET_NULL,
	null = True, verbose_name = "Máquina")
	log_type = models.CharField(max_length = 128, choices = ITEM_LOG_TYPES,
		verbose_name = "Tipo de registro")
	previous_stock = models.PositiveSmallIntegerField(
		default = 0, verbose_name = "Stock previo")
	updated_stock = models.PositiveSmallIntegerField(
		default = 0, verbose_name = "Stock nuevo")
	created_on = models.DateTimeField(default = timezone.now,
		verbose_name = "Creación")


	def __str__(self):
		return f"{self.created_on}"


	class Meta:
		verbose_name = "Registro de Máquinas"
		verbose_name_plural = "Registros de Máquinas"
		db_table = "machine_log"


class MachinesSupplyLog(models.Model):

	user = models.ForeignKey(User, on_delete = models.SET_NULL,
	null = True, verbose_name = "Usuario")
	machines_supply = models.ForeignKey(MachinesSupply, on_delete = models.SET_NULL,
	null = True, verbose_name = "Suministro para máquinas")
	log_type = models.CharField(max_length = 128, choices = ITEM_LOG_TYPES,
		verbose_name = "Tipo de registro")
	previous_stock = models.PositiveSmallIntegerField(
		default = 0, verbose_name = "Stock previo")
	updated_stock = models.PositiveSmallIntegerField(
		default = 0, verbose_name = "Stock nuevo")
	created_on = models.DateTimeField(default = timezone.now,
		verbose_name = "Creación")


	def __str__(self):
		return f"{self.created_on}"


	class Meta:
		verbose_name = "Registro de Suministros de Máquinas"
		verbose_name_plural = "Registros de Suministros de Máquinas"
		db_table = "machines_supply_log"


class UnclassifiedItemLog(models.Model):

	user = models.ForeignKey(User, on_delete = models.SET_NULL,
	null = True, verbose_name = "Usuario")
	unclassified_item = models.ForeignKey(UnclassifiedItem, on_delete = models.SET_NULL,
	null = True, verbose_name = "Ítem")
	log_type = models.CharField(max_length = 128, choices = ITEM_LOG_TYPES,
		verbose_name = "Tipo de registro")
	previous_stock = models.PositiveSmallIntegerField(
		default = 0, verbose_name = "Stock previo")
	updated_stock = models.PositiveSmallIntegerField(
		default = 0, verbose_name = "Stock nuevo")
	created_on = models.DateTimeField(default = timezone.now,
		verbose_name = "Creación")


	def __str__(self):
		return f"{self.created_on}"


	class Meta:
		verbose_name = "Registro de Ítems sin clasificar"
		verbose_name_plural = "Registros de Ítems sin clasificar"
		db_table = "unclassified_item_log"


class CustomLogType(models.Model):

	name = models.CharField(max_length = 255, unique = True, 
						 verbose_name = "Nombre")
	index = models.PositiveSmallIntegerField(
		default = 1,
		help_text = "El valor de índice permite ordenar los tipos de registro según prioridad.", 
		verbose_name = "Índice"
		)
	in_use = models.BooleanField(
		default = True,
		help_text = "Se puede desactivar esta casilla si se quiere dejar de usar este tipo de registro.", 
		verbose_name = "En uso"
		)


	def __str__(self):
		return self.name
	

	class Meta:
		verbose_name = "Tipo de Registros personalizados"
		verbose_name_plural = "Tipos de Registros personalizados"
		db_table = "custom_log_type"
		ordering = ("index", "name")


class CustomLog(models.Model):

	user = models.ForeignKey(User, on_delete = models.SET_NULL,
		null = True, verbose_name = "Usuario")
	log_type = models.ForeignKey(CustomLogType, on_delete = models.DO_NOTHING,
							  verbose_name = "Tipo de registro")
	priority = models.CharField(max_length = 30, choices = PRIORITIES,
		default = "", verbose_name = "Prioridad")
	created_on = models.DateTimeField(default = timezone.now,
		verbose_name = "Creación")
	updated_on = models.DateTimeField(auto_now_add = True,
		verbose_name = "Última actualización")
	is_archived = models.BooleanField(default = False,
		verbose_name = "Archivado")
	description = models.TextField(verbose_name = "Descripción")
	

	def __str__(self):
		return f"Registro con ID {self.id}"


	class Meta:
		verbose_name = "Registro personalizado"
		verbose_name_plural = "Registros personalizados"
		db_table = "custom_log"

logbook/forms.py
from django import forms
from .models import *


class CustomLogForm(forms.ModelForm):

	class Meta:
		model = CustomLog
		fields = ["log_type", "priority", "description"]

	log_type = forms.ModelChoiceField(
		queryset = CustomLogType.objects.filter(in_use = True).all(),
		widget = forms.Select(
			attrs = {"class": "form-select"}
			),
		label = "Tipo de registro"
		)
	priority = forms.ChoiceField(
		choices = PRIORITIES,
		widget = forms.Select(
			attrs = {"class": "form-select"}
			),
		label = "Prioridad"
		)
	description = forms.CharField(
		widget = forms.Textarea(
			attrs = {
				"class": "form-control",
				"rows": 4,
				}
			),
		label = "Descripción"
		)

logbook/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, Http404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from .models import CustomLog
from .forms import CustomLogForm
from utils.telegram_bot import send_bot_message
from utils.decorators import superuser_required

# Create your views here.

@login_required
def logbook_home(request):

	custom_logs = CustomLog.objects.filter(is_archived = False).all()
	archived_custom_logs = CustomLog.objects.filter(is_archived = True).all()

	context = {
		"title": "Sección de Bitácora",
		"custom_logs": custom_logs,
		"archived_custom_logs": archived_custom_logs,
	}

	return render(request, 'logbook/logbook_home.html',
		context)


# Vista para crear un registro personalizado
@login_required
def logbook_new_custom_log(request):

	if request.method == "POST":
		form = CustomLogForm(request.POST or None)

		if form.is_valid():
			data = form.cleaned_data

			new_custom_log = CustomLog(
				user = request.user,
				log_type = data["log_type"],
				priority = data["priority"],
				description = data["description"]
			)

			new_custom_log.save()

			messages.add_message(request, messages.SUCCESS,
			"Registro creado exitosamente")

			# enviar mensaje con el bot
			message_text = f"El usuario *{request.user.first_name} {request.user.last_name}* ha creado un registro personalizado de tipo *{new_custom_log.log_type.name}* en la *Bitácora*."
			send_bot_message(message_text)

			# redirigir a la página de inicio
			return HttpResponseRedirect(reverse('logbook_home'))

	else:
		form = CustomLogForm()

	context = {
		"title": "Crear nuevo registro",
		"form": form
	}

	return render(request, 'logbook/logbook_new_custom_log.html',
		context)


# Vista para ver/editar un registro personalizado
@login_required
def logbook_custom_log_detail(request, id):
	custom_log = get_object_or_404(CustomLog, id = id)

	context = {
		"title": "Información de Registro",
		"custom_log": custom_log
	}

	return render(request, 'logbook/logbook_custom_log_detail.html',
		context)


# Vista para archivar un registro personalizado
@superuser_required
def logbook_switch_custom_log_archived_status(request, id):
	custom_log = get_object_or_404(CustomLog, id = id)

	custom_log.is_archived = not custom_log.is_archived
	custom_log.save()
	print(custom_log.is_archived)

	if custom_log.is_archived:

		alert_message = "El registro se ha archivado correctamente."
		message_text = f"El Registro Personalizado con *ID {custom_log.id}* ha sido archivado, y ya no estará visible en la Bitácora."

	else:

		alert_message = "El registro se ha desarchivado correctamente."
		message_text = f"El Registro Personalizado con *ID {custom_log.id}* ha sido desarchivado, y vuelve a estar visible en la Bitácora."

	send_bot_message(message_text)

	messages.add_message(request, messages.INFO,
		alert_message)

	return HttpResponseRedirect(reverse('logbook_home'))

templates/logbook/archived_custom_logs_table.html
<div class="table-responsive">
	<table class="table responsive display dataTable">
		<thead>
			<tr>
				<th scope="col">ID</th>
				<th scope="col">Creación</th>
				<th scope="col">Tipo</th>	
				<th scope="col">Prioridad</th>
				<th scope="col">Creado por</th>
			</tr>
		</thead>
		<tbody>
			{% for log in archived_custom_logs %}
				<tr>
					<td>
						<a href="{% url 'logbook_custom_log_detail' log.id %}" class="text-dark-green-link">{{log.id}}</a>
					</td>
					<td>{{log.created_on}}</td>
					<td>{{log.get_log_type_display}}</td>
					<td>{{log.get_priority_display}}</td>
					<td>{{log.user.first_name}} {{log.user.last_name}}</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
</div>

templates/logbook/custom_log_form.html
<form method="post" id='saveForm'>{% csrf_token %}

	<div class="row g-3">
		<div class="col-md-6">
			<label for="log_type" class="form-label fw-bold">{{form.log_type.label}}</label>
			{{form.log_type}}
		</div>
		<div class="col-md-6">
			<label for="priority" class="form-label fw-bold">{{form.priority.label}}</label>
			{{form.priority}}	
		</div>
	</div>		
	
	<div class="my-3">
		<label for="description" class="form-label fw-bold">{{form.description.label}}</label>
		{{form.description}}
	</div>		
	
	<hr>
	<a href="javascript:void(0);" class="btn btn-green" id='submitButton'>Guardar</a>
</form>

templates/logbook/custom_logs_table.html
{% load tz %}
<div class="table-responsive">
	<table class="table responsive display dataTable">
		<thead>
			<tr>
				<th scope="col">ID</th>
				<th scope="col">Creación</th>
				<th scope="col">Tipo</th>	
				<th scope="col">Prioridad</th>
				<th scope="col">Creado por</th>
			</tr>
		</thead>
		<tbody>
			{% for log in custom_logs %}
				<tr>
					<td>
						<a href="{% url 'logbook_custom_log_detail' log.id %}" class="text-dark-green-link">
							{{log.id}}
						</a>
					</td>
					<td>{{log.created_on}}</td>
					<td>{{log.log_type.name}}</td>
					<td>{{log.get_priority_display}}</td>
					<td>{{log.user.first_name}} {{log.user.last_name}}</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
</div>

templates/logbook/logbook_custom_log_detail.html
{% extends 'base/base.html' %} {% load static %}

{% block title %}{{title}}{% endblock title%}

{% block body %}

<div class="container-fluid rounded border px-5 py-4 bg-white">

	<h2 class="text-center text-green">{{title}} <span class="text-brown">{{custom_log.id}}</span></h2>

	<hr class="text-brown">

	<div class="row g-3">
		<div class="col-md-6">
			<p><span class="fw-bold">ID: </span>{{custom_log.id}}</p>	
		</div>
		<div class="col-md-6">
			<p><span class="fw-bold">Tipo: </span>{{custom_log.log_type.name}}</p>		
		</div>
		<div class="col-md-6">
			<p><span class="fw-bold">Prioridad: </span>{{custom_log.get_priority_display}}</p>		
		</div>
		<div class="col-md-6">
			<p><span class="fw-bold">Creación:</span>{{custom_log.created_on}}</p>			
		</div>
		<div class="col-md-6">
			<p><span class="fw-bold">Creado por: </span>{{custom_log.user.first_name}} {{custom_log.user.last_name}}</p>		
		</div>
		<div class="col-md-6">
			<p>
				<span class="fw-bold">Estado: </span>
				{% if custom_log.is_archived %}
				<span class="text-danger">Archivado</span>
				{% else %}
				<span class="text-success">Visible</span>
				{% endif %}
			</p>		
		</div>
		<div class="col-12">
			<label class="form-label fw-bold">Descripción:</label>
			<p>{{custom_log.description}}</p>
		</div>
	</div>

	<hr>

	{% if user.is_superuser %}
	<p>Los superusuarios pueden archivar o desarchivar este registro de ser necesario.</p>
		{% if custom_log.is_archived %}
			<a href="{% url 'logbook_switch_custom_log_archived_status' custom_log.id %}" id="unarchiveButton" class="btn btn-green">Desarchivar</a>
		{% else %}
			<a href="{% url 'logbook_switch_custom_log_archived_status' custom_log.id %}" id="archiveButton" class="btn btn-purple">Archivar</a>
		{% endif %}
	{% endif %}

</div>

{% endblock body %}

templates/logbook/logbook_home.html
{% extends 'base/base.html' %}{% load static %}{% load tz %}

{% block title %}{{title}}{% endblock title %}

{% block body %}

{% include 'base/base_messages.html' %}

<div class="container-fluid rounded px-5 py-4 bg-white mb-3">
	<h1 class="text-center text-green">{{title}}</h1>
	<p>Cada uno de los ítems registrados en el inventario de Regulus tiene su propia bitácora, así que, para buscar un registro, se debe buscar en el ítem correspondiente. Sin embargo, está disponible esta sección que permite crear <strong>Registros personalizados</strong>, para uso interno. Solo los usuarios autorizados tienen acceso a esta sección.</p>	

</div>


<div class="container-fluid rounded px-5 py-4 bg-white mb-3">

	<h2 class="text-center text-brown">Registros</h2>

	{% include 'logbook/custom_logs_table.html' %} 
	
	<br>

	<a href="{% url 'logbook_new_custom_log' %}" class="btn btn-green">
		Nuevo registro
	</a>

</div>

{% if user.is_superuser %}

<div class="container-fluid rounded border px-5 py-4 bg-white">

	<h2 class="text-center text-brown">Registros archivados</h2>

	{% include 'logbook/archived_custom_logs_table.html' %}
	
	<br>

</div>
{% endif %}


{% endblock body %}

templates/logbook/logbook_new_custom_log.html
{% extends 'base/base.html' %} {% load static %}

{% block title %}{{title}}{% endblock title%}

{% block body %}

<div class="container-fluid rounded px-5 py-4 bg-white">

	<h1 class="text-center text-green">{{title}}</h1>
	<p>Puede utilizar el siguiente formulario para crear un nuevo Registro personalizado en la Bitácora. Todos los campos son obligatorios.</p>

	<p><strong>Revise bien antes de guardar</strong>, ya que el registro no podrá modificarse posteriormente.</p>

	<hr>

	{% include 'base/base_form_errors.html' %}

	{% include 'logbook/custom_log_form.html' %}

</div>

{% endblock body %}

templates/logbook/logs_table.html
<div class="table-responsive">
	<table class="table responsive display dataTable">
		<thead>
			<tr>
				<th scope="col">Fecha/hora</th>
				<th scope="col">Tipo</th>
				<th scope="col">Stock previo</th>
				<th scope="col">Stock nuevo</th>
				<th scope="col">Usuario</th>
			</tr>
		</thead>
		<tbody>
			{% for log in logs %}
				<tr>
					<td>{{log.created_on}}</td>
					<td>{{log.get_log_type_display}}</td>
					<td>{{log.previous_stock}}</td>
					<td>{{log.updated_stock}}</td>
					<td>{{log.user}}</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
</div>